### PR TITLE
Modify warning logic in WindowsJNAAffinity.setAffinity

### LINKED ISSUE #117: setAffinity does not work as expected in Windows
On win 11 got warning:
            "Tried to set affinity to {7} but was {0,1,2,3,4,5,6,7} you may have insufficient access rights"
and nohing heppend - thread remain affined to all cores.

Java version: jdk-21.0.2.13-hotspot (Eclipse Adoptium)
jna and jna-platform  verstion: 5.14.0
affinity version: 3.23.3

Thread, for which i try to lock affiniti created by :

Thread.ofPlatform().name("AffinedThread").start(() -> {
    try (AffinityLock al = AffinityLock.acquireLock()) {
       .....
   }
});

Starting console in which java started with Admin rights change nothing.

### PR DESCRIPTION
**Pull request by yevgenp**
Closes #117

### CODE REVIEW

**Review by tgd — CHANGES_REQUESTED** [review]
Hi @yevgenp thanks for sorting this out :+1: 

Please can you get the Windows build green before merging - I believe it has been broken for a while but this is a good opportunity to fix it.

File: affinity/src/main/java/net/openhft/affinity/impl/WindowsJNAAffinity.java [hunk 1]
```diff
@@ -89,7 +89,7 @@ public void setAffinity(final BitSet affinity) {
             throw new IllegalStateException("SetThreadAffinityMask((" + pid + ") , &(" + affinity + ") ) errorNo=" + e.getErrorCode(), e);
         }
         BitSet affinity2 = getAffinity0();
-        if (!affinity2.equals(affinity)) {
+        if (!affinity2.intersects(affinity)) {
```
Comment (tgd) [inline affinity/src/main/java/net/openhft/affinity/impl/WindowsJNAAffinity.java:93]: Is it possible to cover this with a Windows specific unit test?

Comment (yevgenp) [reply affinity/src/main/java/net/openhft/affinity/impl/WindowsJNAAffinity.java:93]: That warning is being produced on **every** Windows test (except when run on a single CPU). IMO it would not yield too much value to test a single log line. Especially, when we can't reproduce a negative case.
